baseURL: "https://gabriellazcano.com"
languageCode: "en-us"
title: "Gabriel Lazcano"
copyright: "Â© 2021 Gabriel Lazcano"

params:
  author: "Gabriel Lazcano"
  codepenUser: "DatsGabs"

menu:
    blog:
        - identifier: archive
          name: Archive
          url: /archive
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags
          weight: 10
        - identifier: newsletter
          name: Newsletter
          url: /newsletter
          weight: 30

taxonomies: 
  tag: tags

sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

markup:
  highlight:
    noClasses: false
    tabWidth: 4